server:
  port: 8088
springdoc:
  swagger-ui:
    path: /
    operationsSorter: method
spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate.show_sql: true
    #database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: cms
    password: cms